const mongoose = require("mongoose");

const Hospitals = mongoose.model("hospitals", {
  Sr_No: Number,
  Location_Coordinates: String,
  Location: String,
  Hospital_Name: String,
  Hospital_Category: Number,
  Hospital_Care_Type: String,
  Discipline_Systems_of_Medicine: String,
  Address_Original_First_Line: String,
  State: String,
  District: String,
  Subdistrict: Number,
  Pincode: Number,
  Telephone: String,
  Mobile_Number: Number,
  Emergency_Num: Number,
  Ambulance_Phone_No: Number,
  Bloodbank_Phone_No: Number,
  Foreign_pcare: Number,
  Tollfree: Number,
  Helpline: Number,
  Hospital_Fax: Number,
  Hospital_Primary_Email_Id: Number,
  Hospital_Secondary_Email_Id: Number,
  Website: Number,
  Specialties: Number,
  Facilities: Number,
  Accreditation: Number,
  Hospital_Regis_Number: Number,
  Registeration_Number_Scan: Number,
  Nodal_Person_Info: Number,
  Nodal_Person_Tele: Number,
  Nodal_Person_Email_Id: Number,
  Town: Number,
  Subtown: Number,
  Village: Number,
  Establised_Year: Number,
  Ayush: Number,
  Miscellaneous_Facilities: Number,
  Number_Doctor: Number,
  Num_Mediconsultant_or_Expert: Number,
  Total_Num_Beds: Number,
  Number_Private_Wards: Number,
  Num_Bed_for_Eco_Weaker_Sec: Number,
  Empanelment_or_Collaboration_with: Number,
  Emergency_Services: Number,
  Tariff_Range: Number,
  State_ID: Number,
  District_ID: Number,
});

module.exports = Hospitals;
